### ISSUE TITLE
I'm fresher & plz reply my question. Thanks

### ISSUE THREAD

**Issue by minphone** [saturngod/programming_basic_qa#1]
How can i start to learn OOP? Recently, i attend ACE Training and i studying C# at there. But I can't exactly know about OOP. I really confuse about Interface, Inheritance and other OOP Concert. Can you tell me how can i start to learn about OOP?
Now, I read programming for beginner that you wrote and i can't understand about general use mean at 4th generation language.
Thanks........

**Comment by saturngod** [comment]
http://books.saturngod.net/programming_basic/CH1/programminglanguage.html က အပိုင်းကို နားမလည်တာလား ဒါမှမဟုတ် ဘယ်အပိုင်းကို နားမလည်တာလည်း မသိဘူး ?

**Comment by saturngod** [comment]
OOP အကြောင်းကိုတော့ အခန်း ၃ မှာ ရှင်းပြထားပါတယ်။ http://books.saturngod.net/programming_basic/CH3/index.html

**Comment by minphone** [comment]
ch1 မှာ general use ရဲ့ mean ကိုသိပ်နားမလည်တာပါ။

**Comment by minphone** [comment]
OOP အကြောင်းက အခန်း၃ ကိုနားလည်ယုံနဲ့ လုံလောက်ပါသလား။

**Comment by saturngod** [comment]
မလုံလောက်ပါဘူး။ OOP ကို python မှာ အများကြီး ပြောလို့ မရဘူး။ OOP အတွက် java သို့မဟုတ် C++ ကို လေ့လာရင် နားလည်ဖို့ ပိုလွယ်မယ်။
