### ISSUE TITLE
wanted to know something like Ubuntu Debian Linux Terminal 

### ISSUE THREAD

**Issue by shelay221** [saturngod/programming_basic_qa#10]

**Comment by shelay221** [comment]
![python](https://user-images.githubusercontent.com/62051975/76398562-7911f980-63ab-11ea-94be-d7021532a37c.png)

**Comment by saturngod** [comment]
အခု ပုံက terminal ထဲ ဝင်သွားတာပါ။ exit() နဲ့ ပြန်ထွက်နိုင်ပါတယ်။
