### ISSUE TITLE
Need to understand more 

### ISSUE THREAD

**Issue by waiyankyaw961999** [saturngod/programming_basic_qa#11]
```py
class Stack:
    def __init__(self):
        self.items = []
    def is_empty(self):
        return self.items == []
    def push(self, item):
        self.items.append(item)
    def pop(self):
        return self.items.pop()
    def peek(self):
        return self.items[len(self.items) - 1]
    def size(self):
        return len(self.items)

s = Stack()
print(s.is_empty())
s.push(4)
s.push('dog')
print(s.peek())
s.push(True)
print(s.size())
s.push(8.4)
print(s.pop())
print(s.pop())
print(s.size())
```
I want to know more about this, because I've felt I don't fully comprehend the way it works.
My gmail>> waiyankyawmc@mtu.edu.mm
my skype>>live:casperlay210
If i can ask you directly from either gmail or skype, could u pls provide with your answer?

**Comment by saturngod** [comment]
@waiyankyaw961999  , python မှာ tab တွေက အရေးပါပါတယ်။ Block ပုံစံ ဖြစ်သည့် အတွက်ကြောင့် စနစ်ကျဖို့ လိုပါတယ်။

ကျွန်တော် python code ကို block တွေ မှန်အောင် ပြန်ဖြည့်ထားပါတယ်။

https://repl.it/repls/FortunateWeightyPlot

မှာ ကြည့်ကြည့်ပါ

**Comment by waiyankyaw961999** [comment]
Thank for replying me . I've just comprehended how stack works. Now, i'm reading your queue. Thank you.

**Comment by waiyankyaw961999** [comment]
Sir I’m not familiar with creating class in python. I’m a newer to python. In your book, creating class Node for unordered list gives me headache!
To be able to understand well, could u pls suggest me from where  I do have to start?
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by saturngod** [comment]
စာအုပ်နဲ့ video တွဲကြည့်ကြည့်ပါ။ 

https://www.youtube.com/watch?v=JPMPG8AQFbw

https://www.youtube.com/watch?v=FR4Gkj_GPG8

နားမလည်ရင် မေးလို့ရပါတယ်။ ကျွန်တော် အတတ်နိုင်ဆုံး နားလည်အောင် ရှင်းပြပေးပါမယ်။
