### ISSUE TITLE
please explain Fibonacci Question 

### ISSUE THREAD

**Issue by ye-phyo** [saturngod/programming_basic_qa#12]
```python
x = input("Total number : ")
try :
    x = int(x)
    f = 0
    s = 1;

    for k in range(x):
        print(s, end=" ") # end is for ending with space and don't use another line
        t = s
        s = f + s
        f = t
        print ("") #just for line break in terminal
except ValueError:
    print("Please enter number only")
```
Line 8 ကစပြီး နားမလည်တော့လို့ ရှင်းပြပေးစေလိုပါတယ်ခင်ဗျ

**Comment by saturngod** [comment]
Fibonacci Sequence ကို မေးထားတာထင်ပါတယ်။

Fibonacci Sequence က 1 , 1 , 2, 3, 5 ဆိုပြီး ရှိတယ်။ 1 က စတယ်။ ရှေ့ ကိန်း ၂ လုံးပေါင်းက နောက်ကိန်း ရတယ်။ 

1 + 1 = 2
1 + 2 = 3
2+ 3 = 5
3 + 5 = 8
5 + 8  = 13

အဲဒီ ပုံစံနဲ့ ပေါင်းသွားတာပါ။

f က ရှေ့ စာလုံး​  ပါ။ ဒါကြောင့် စတော့ ၀ နဲ့ စတယ်။ s က ဒုတိယ စာ လုံး။​ ဒါကြောင့် စတော့ ၁ နဲ့ စတယ်။

t က temporary ပါ။ ဒုတိယ စာလုံးက ရှေ့ နဲ့ ဒုတိယ ပေါင်းရင် ရသည့် စာလုံး။​ overwrite ဖြစ်သွားမှာ ဖြစ်သည့် အတွက်ကြောင့် t ထဲမှာ အရင်ထည့်ထားပါတယ်။

ပြီးမှ​ဒုတိယ စာလုံးက ပထမ ပြန် ဖြစ်သည့်အတွက် f ထဲကို ပြန်ထည့်ပေးပါတယ်။

**Comment by ye-phyo** [comment]
ကျေးဇူးပါဆရာ
