### ISSUE TITLE
Hi Sir

### ISSUE THREAD

**Issue by TheinThu13** [saturngod/programming_basic_qa#14]
Hi Sir
ကျွန်တော်သိချင်တဲ့ဟာ မေးချင်လို့ပါ Sir

A, B, C, D, E, F, G, H, I, J အဲ့စာလုံး ၁၀ လုံးကို မတူတဲ့စကားစုအဖြစ် သူ့ဘာသာ auto လုပ်ချင်တာ Sir (စကားစုအလုံး ၁၀၀ ရှိမယ်ဆိုရင် အလုံး ၁၀၀ အကုန်လုံးပေါ့ Sir)
ဥပမာ ဒီလိုလေးပေါ့ Sir

1. A B C D E F G H I J
2. A B C D E F G H J I
3. A B C D E F G J H I . . . . J I H G F E D C B A

အဲ့လိုလုပ်ဖို့ဖြစ်နိုင်လား Sir
လုပ်ဖို့ဖြစ်နိုင်ရင် ဘယ်ဟာတေကိုလေ့လာရမလဲ Sir

**Comment by saturngod** [comment]
Shuffle String လုပ်ချင်တာလား ?

```python
import random
s="ABCDEFGHIJ"
print(''.join(random.sample(s,len(s))))
```

ကို စမ်းကြည့်ပါ

**Comment by TheinThu13** [comment]
ဟုတ် Sir အဲ့လိုမျိုး sir
Sir ကျွန်တော်မသိလို့မေးတာပါ အခါ ၂၀/၃၀ လောက်တစ်ခါတည်းလုပ်လို့ရနိုင်လား Sir 
အခုလုပ်ကြည့်တာတော့ ၁ ခါကို စကားစု ၁ ခုတော့ရတယ် Sir

**Comment by saturngod** [comment]
အခါ ၂၀ လောက်လိုချင်ရင် loop ပတ်လိုက်ရင်ရပါတယ်။ for loop နဲ့ အကြိမ် ၂၀ ပတ် လိုက်ပါ။
