### ISSUE TITLE
Request for unicode version

### ISSUE THREAD

**Issue by nyanlinnaung** [saturngod/programming_basic_qa#2]
How can i have unicode version of the book? I know i can use mm font convertor plugin to read but i have to download the book site with wget so using browser plugin to read is not possible.

**Comment by ljknee** [comment]
Insert plugin in your browser from this [URL](http://mrdba.info/2016/07/muaconverter/).
Don't need to worry for Myanmar font problem.

**Comment by saturngod** [comment]
no plan to support with unicode in website.
