### ISSUE TITLE
သင်ခန်းစာအချို့ တွင် code များ run လို့မရ

### ISSUE THREAD

**Issue by TRSoe** [saturngod/programming_basic_qa#4]
programming basic သင်ခန်းစာ အချို့ တွင် run လို့ မရပါ File "stack", line 1
    <!Doctype html>
SyntaxError: invalid syntax
အဲ့လို ပြနေပါတယ်
တချို့ သင်ခန်းစာ များတွင်လည်း အလားတူ message များပြပြီး code run လို့မရပါ

**Comment by TRSoe** [comment]
ရတဲ့ အခါ ကျ လည်း ရနေ ပြန်တယ် အဲ့ အမှား က ခနခန တွေ့ နေရတယ်

**Comment by saturngod** [comment]
ဘယ်အခန်း နံပတ်  မှာ ဖြစ်တာလဲ ခင်ဗျာ။ ကျွန်တော် ပြန်စစ်ပေးပါမယ်။ link ဖြင့် အတိအကျပြောပေးပါ။

**Comment by TRSoe** [comment]
http://books.saturngod.net/programming_basic/CH5/priorityqueue.html ကျ နော် အခုစမ်းကြည့်နေတာတော့ အခန်း ၅ က တစ်ခန်းလုံး နီးပါး ဖြစ်နေတယ် စောစော က stack အခန်း မှာ  အဲ့ လို ပြပြီး နောက် တစ်ခါ ထပ်စမ်းတော့ ရသွားပြန်တယ်

**Comment by saturngod** [comment]
ဘယ် browser ကို အသုံးပြုလဲ မသိဘူးခင်ဗျ ? ကျွန်တော် chrome နဲ့ စမ်းကြည့်တာ အဆင်ပြေပါတယ်။ နောက်ပြီးတော့ connection မကောင်းရင် run ဖို့ အတွက် file download ချတာ အနည်းငယ်ကြာတတ်ပါတယ်။

**Comment by TRSoe** [comment]
mozilla firefox ပါ ဆရာ 
![screenshot from 2017-03-19 11 39 06](https://cloud.githubusercontent.com/assets/25982382/24078323/f374a1fe-0c98-11e7-8944-5d4a45d16c48.png)
အဲ့ လိုတွေတစ်ခါတစ်ခါပေါ်နေတာပါ

**Comment by saturngod** [comment]
ကျွန်တော် အခု စမ်းကြည့်တာ အဆင်ပြေတယ်။ refresh ပြန်လုပ်ကြည့်ပါလား။ အခြား firefox မှာ plugin တွေ အသုံးပြုထားသေးလား ? ဖြစ်နိုင်တာက အခြား plugin တစ်ခုခု နဲ့ ညှိနေတာကြောင့်လည်း ဖြစ်နိုင်ပါတယ်။

**Comment by TRSoe** [comment]
ရသွားပြီ အဲ့လို ပြနေရင် refresh လုပ်ကြည့်လိုက်တာ အဆင် ပြေသွားတယ် ကျေးဇူးပါဆရာ
