### ISSUE TITLE
if not in python

### ISSUE THREAD

**Issue by TRSoe** [saturngod/programming_basic_qa#5]
top = s.pop()
if not matches(top,symbol):
    balanced = False
အဲ့ code မှာ if not ဆိုတဲ့ အသုံးကို သိပ်မရှင်းဘူး ဖြစ်နေတယ် ရှင်းပြပေးပါအုံး ခင်ဗျာ

**Comment by saturngod** [comment]
if not ဆိုတာကတော့  အဲဒါ မဟုတ်ခဲ့ရင်ကို ဆိုတာပါ။

```
if not False 
```

ဆိုသည့် အဓိပ္ပာယ်ကတော့

```
if True
```

ဆိုသည့် အဓိပ္ပာယ် နဲ့ အတူတူပါပဲ။

```
if not True 
```

ဆိုရင်တော့

```
if False
```

နဲ့ တူတာပေါ့။

**Comment by saturngod** [comment]
```
if not 5 == 6 :
    print("HI")
```

ဆိုတာကတော့ 5 နဲ့ 6 က တူတာ မဟုတ်ခဲ့ရင် ဒီ condition မှန်တယ် ။ HI ကို print ထုတ်လို့ ဆိုပါတယ်။

အဓိပ္ပာယ်ကတော့

```
if 5 != 6 :
    print("HI")
```

နဲ့ အတူတူပါပဲ။

**Comment by TRSoe** [comment]
ဟုတ် နားလည်သွားပြီ ကျေးဇူးပါ
