### ISSUE TITLE
chapter 9 parse မှာ code run မရ

### ISSUE THREAD

**Issue by TRSoe** [saturngod/programming_basic_qa#6]
![screenshot from 2017-06-19 20 26 54](https://user-images.githubusercontent.com/25982382/27288893-288bb408-552e-11e7-8887-377fc0ebd0a3.png)

**Comment by TRSoe** [comment]
![screenshot_2017-06-19-20-25-36](https://user-images.githubusercontent.com/25982382/27289534-427cf0e6-5530-11e7-8fed-7c03e29639b7.png)
moblie browser မှာလည်း run ကြည့်ထားပါတယ် refresh လည်းလုပ်ကြည့်ထားပါတယ် အရင် အခန်းတွေမှာ တော့ refresh လုပ်ရင် run လို့ရသွားပါတယ်

**Comment by saturngod** [comment]
server config ကြောင့် ပြသနာ ဖြစ်သွားပါတယ်။ ပြန် စမ်းကြည့်ပေးပါ။
