### ISSUE TITLE
can not run python on my ubuntu

### ISSUE THREAD

**Issue by MyoMinnThant9** [saturngod/programming_basic_qa#9]
ဟယ်လို . ကိုထိန်းလင်းရေ  ကျွန်တော်စက်မှာ  Python က ရှိတယ် ခင်ဗျ...number လက်ခံတဲ့အခါ ပုံမှာ ပြထားတဲ့အတိုင်းဖြစ်နေလို့ပါခင်ဗျ။ လုပ်တာမှားနေလားမသိဘူးခင်ဗျ..လမ်းညွန်ပေးပါဦးခင်ဗျ...
![Screenshot from 2019-06-06 15-12-49](https://user-images.githubusercontent.com/46397864/59019287-ca65e900-886d-11e9-99a1-289ff5c7ee2e.png)

**Comment by saturngod** [comment]
code ကို 

x = input ("First Number : ")

ဆိုရင် First Number: ဆိုပြီး တက်လာမယ်။ number ရိုက်ထည့် ရုံပါပဲ။

<img width="682" alt="Screen Shot 2019-06-12 at 10 03 12 am" src="https://user-images.githubusercontent.com/135177/59321805-6cb41f80-8cf9-11e9-8d42-2e756b1782a9.png">

**Comment by MyoMinnThant9** [comment]
Well received with thanks, Ko Saturngod.
